# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 23:05
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Avaluo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=100, verbose_name='Dirreccion del inmueble')),
                ('tipoImmueble', models.CharField(max_length=50, verbose_name='Tipo del inmueble')),
                ('banos', models.CharField(max_length=10, verbose_name='Ba\xf1os')),
                ('area_construida', models.DecimalField(decimal_places=0, default=0, max_digits=20)),
                ('estrato', models.CharField(max_length=10, verbose_name='Area construida')),
                ('fecha_Cons', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Construccion')),
                ('administracion', models.DecimalField(decimal_places=0, default=0, max_digits=20)),
                ('deposito', models.BooleanField(verbose_name='Deposito')),
                ('ascensor', models.BooleanField(verbose_name='Ascensor')),
                ('vigilancia', models.BooleanField(verbose_name='Vigilancia')),
                ('conjunto_cerrado', models.BooleanField(verbose_name='Conjunto Cerrado')),
                ('gimnasio', models.BooleanField(verbose_name='gimnasio')),
                ('parqueadero', models.BooleanField(verbose_name='Parqueadero')),
                ('precio', models.DecimalField(decimal_places=0, default=0, max_digits=20)),
                ('precioCalc', models.DecimalField(decimal_places=0, default=0, max_digits=20)),
                ('Lat', models.FloatField()),
                ('Long', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
    ]
